services:
  redis:
    image: 'redis:latest'
    ports:
      - '6379'
  postgres:
    image: 'postgres:latest'
    environment:
      - 'POSTGRES_DB=demo'
      - 'POSTGRES_PASSWORD=demo'
      - 'POSTGRES_USER=demo'
    command: postgres -c 'max_connections=500'
    ports:
      - '5432'
    labels:
      org.springframework.boot.jdbc.parameters: reWriteBatchedInserts=true
