services:
  postgres:
    image: 'postgres:latest'
    environment:
      - 'POSTGRES_DB=demo'
      - 'POSTGRES_PASSWORD=demo'
      - 'POSTGRES_USER=demo'
    command: postgres -c 'max_connections=500'
    ports:
      - '5432'
